env:
  node: false

plugins:
  - angular

rules:
  no-console: 2 # disallow use of console - use logging library instead
  strict: [2, "function"] # controls location of Use Strict Directives
  max-params: [2, 11] # limits the number of parameters that can be used in the function declaration.
  angular/controller-as: 2
  angular/controller-as-route: 2
  angular/controller-as-vm: [2, 'vm']
  angular/controller-name: [1, '/[A-Z].*Controller$/']
  angular/directive-name: [1, '/[A-Z].*Directive$/']
  angular/service-name: [1, '/[A-Z].*Service$/']
  angular/di: [2, 'function']
  angular/document-service: 2
  angular/interval-service: 2
  angular/json-functions: 2
  angular/no-digest: 2
  angular/no-private-call: 2
  angular/on-watch: 2
  angular/timeout-service: 2
  angular/window-service: 2
  angular/no-service-method: 1
  angular/no-services: 1

globals:
  angular: false
  beforeEach: false
  describe: false
  expect: false
  inject: false
  it: false
  module: false
  sinon: false
